### ISSUE TITLE
Move tests to GitHub Actions

### ISSUE THREAD

**Issue by nicolasstucki** [scala/scala3-cross.g8#17]

**Comment by SethTisue** [comment]
@nicolasstucki is there someone at LAMP or the Scala Center who could tackle this (and other Scala 3 repos under the scala/*) umbrella as part of https://github.com/scala/scala-dev/issues/785 ?

**Comment by sjrd** [comment]
The scala3-* repos are more under the control of LAMP, so I'll let them do it, unless they ask me to. ;-)

**Comment by nicolasstucki** [comment]
I can take care of it
